version: "3"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: ./.devcontainer/Dockerfile
      args:
        VARIANT: 3
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/workspace:cached

    command: sleep infinity
    network_mode: service:db
    user: vscode

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
