version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: ./.devcontainer/Dockerfile
      args:
        VARIANT: 3
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - .:/workspace:cached

    command: sleep infinity
    network_mode: service:db
    user: vscode
